# modified from standard jekyll configuration options

exclude:
  - app
  - templates
  - README.md
  - stack.yaml
  - _cache

# configuration required for some pages

domain: bvenner.github.io
title: Semiotics, Statistics, and All That
author:
  name: Brad Venner
  givenName: Brad
  familyName:  Venner
  twitter:  BradVenner
  github:  bvenner
  email: brad@vennerconsulting.com
url:  http://bvenner.github.io

markdown:  pandoc
markdown_ext:  markdown, md
pandoc:
  extensions:
    - smart
    - mathjax

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid
