# modified from standard jekyll configuration options

exclude:
  - app
  - templates
  - stack.yaml
  - _cache
  - _rmd
  - stack.yaml

# configuration required for some pages
theme:  minima
domain: bvenner.github.io
title: Semiotics, Statistics, and All That
author:
  name: Brad Venner
  givenName: Brad
  familyName:  Venner
  twitter:  BradVenner
  github:  bvenner
  email: brad@vennerconsulting.com
url:  http://bvenner.github.io


#gems:
#  - jekyll-pandoc

#markdown:  pandoc
#markdown_ext:  markdown, md
#pandoc:
#  extensions:
#    - smart
#    - mathjax
#    - bibliography:  biblio/references.yaml

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid
